server:
  port : 8443
logging:
  level:
    org:
      springframework:
        web: DEBUG 
spring:
  h2:
    console: 
      enabled: true
 
---
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect  


---
spring: 
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:mysql://localhost/demo?serverTimezone=UTC
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: update