spring:
  application:
    name: ratedpower-tasks
server:
  port : 8443
logging:
  level:
    org:
      springframework:
        web: DEBUG
management:
  endpoint:
    health:
      probes:
        enabled: true
